# Generated by Django 4.1.5 on 2023-01-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmstakehome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner', models.CharField(max_length=20)),
                ('classes', models.JSONField()),
            ],
        ),
    ]
